FROM ubuntu:22.04

RUN apt-get update && apt-get install -y vlc

# If you want a specific VLC version, specify it in the install command:
# RUN apt-get update && apt-get install -y vlc=3.0.16

CMD ["vlc"] 